# Generated by Django 4.1.7 on 2023-03-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_city_fias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="tnved",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="tnved10",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
