# Generated by Django 4.1.7 on 2023-03-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_item_country_alter_item_tnved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="volume",
            field=models.FloatField(),
        ),
    ]
