# Generated by Django 4.1.7 on 2023-03-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_alter_item_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tnved",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="item",
            name="tnved10",
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
