# Generated by Django 4.1.7 on 2023-03-26 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_alter_item_tnved_alter_item_tnved10"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("cnt", models.IntegerField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="market.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("type_operation", models.CharField(max_length=50)),
                ("cnt", models.IntegerField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="market.region",
                    ),
                ),
            ],
        ),
    ]
