# Generated by Django 4.1.7 on 2023-03-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_rename_data_storeitem_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storeitem",
            options={"ordering": ["-date"]},
        ),
    ]
