# Generated by Django 4.1.7 on 2023-03-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0009_alter_storeitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtransaction",
            name="sender_region_code",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
