# Generated by Django 4.1.7 on 2023-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0010_itemtransaction_sender_region_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storeitem",
            options={"ordering": ["date"]},
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
